//////////// HEROES //////////////////////
1.  CARGAR ATRIBUTOS DE TODOS LOS DOTA2HEROES

//////////// ITEMS //////////////////////
1.

//////////// OTHERS //////////////////////
1.

//////////// ARTICULOS //////////////////////


//////////// MRC //////////////////////
x. PONER QUE UN USUARIO NO PUEDO  POSTEAR DE NUEVO

//////////// SIDESHOP //////////////////////
1.

//////////// PROFILE //////////////////////
1.  TERMINAR ACHIEVEMENTES
3.  TERMINAR ESTADISTICAS - falta seccion achievements
4.  AGREGAR OPCION DE SUSCRIPCION A EMAIL - POSTEOS NUEVOS CON FILTROS DE CUANTOS VOTES TIENE

//////////// SERVER & GENERAL //////////////////////
2.  CONFIGURAR LARAVEL BACKUP -- agregar comnando cron en hosting
3.  COMPROBAR LOS ERRORES N+1 CON LARAVEL 'DEBUG BAR'
4.  MIGRAR HEROES DE DOTAIDEAS
5.  CAMBIAR DOMINIO DE DOTAIDEAS DE HOSTING A HOSTINGER
6.  BORRAR TODOS LOS ->GETMESSAGE() DE EXCEPTIONS
7.  CONFIGURAR EL .ENV EN MODO PRODUCTION
8.  LIMPIAR Y MINIFICAR EL CSS Y EL JS
9.  COMPROBAR MOBILE CSS
10. BORRAR HISTORIAL DE GITHUB POR SI ESTA UNA COPIA DEL .ENV
12. IMPLEMENTAR SISTEMA DE COBROS
13. IMPLEMENTAR SISTEMA DE SHARE CON ESA PAGINA DE VERGA QUE VALIDA TWITTER Y DEMAS
16. UPDATEAR EL UPDATED_AT EN TODOS LOS UPDATES DE POST
XX. ARREGLAR LA SEMANTICA DE TODO EL SITIO H1 H2 H3 ALTS ID VACIOS NAMES VACIOS SECTIONS ETC
XX. AGREAGAR LA INFO OT Y DEMAS METAS EN TODO EL HEAD
xx. COMPLETAR AL MENOS 6 MRC EN EL SEEDER
XX. DAR DE BAJA LOS SEEDERS DE DEV
XX. CAMBIAR EN TODOS LADOS DONDE SE BUSQUE EL ID CON EL POP Y HACER QUE SE BUSQUE EN MOUNTED ASI SOLO PASA AL PRINCIPIO DEL LOAD 
xx. mover donate button a otra pantalla, frena mucho el load del home
xx. crear el menu en mobile de la nav bar









TABLA DE PUNTOS

POSTEAR HEROE 50
POSTEAR ITEM  40
POSTER OTHER  30
COMENTAR       1
MRC PARTICIP  150
MRC WIN       2000 (SCHEDULE)
RECIBIR AWARD 10
VOTAR         8

